### PR TITLE
New dawn

### PR DESCRIPTION
**Pull request by PeterC-DLS**
Rebased off 54b3fd4a5bb895ef18b71a1f17d4bdafbb6ac035 on the 20160902 when neon.1 branch was taken

### CODE REVIEW

**Review by turesheim — APPROVED** [review]
Looks good.

**Comment by PeterC-DLS** [comment]
Great. Can you pull to your repo as a new branch?

**Comment by turesheim** [comment]
Sorry, I think I botched this. Did you want me to create a new branch for these changes? Why not just use the "dawn" branch?

**Comment by PeterC-DLS** [comment]
I couldn't rebase it so ended up cherry picking the changes. If you can rename it as dawn then that would ease @mwebber 's job

**Comment by turesheim** [comment]
Very well, I'll have a look. Sorry about the delay. I've had a week off work.

**Comment by mwebber** [comment]
Um, please don't change the `dawn` branch. That's what the builds for our 4 previous releases of DAWN point to. If you change the `dawn` branch, and later we have to rebuild a previous release of DAWN, we would end up with the newer `launchbar` (which might not even compile with our older target platform).

For us, the `dawn` branch is more like a release tag.

A new branch, maybe called something like `dawn-neon` would be better.

Best of all would be to actually have a release, and publish a `.jar` (with OSGI-friendly manifest, so it can go in the target platform) with a version number. However, I appreciate that might be beyond the scope of this change.

**Pull request merged**
